### ISSUE TITLE
Algorithm improvement

### ISSUE THREAD

**Issue by ichorid** [GuardianLabs/polygon-dash#10]
The algorithms we use for detecting outliers in the stream of transaction-related events and building the reputation score are simplistic and insufficient for the role. We should do a small research on state-of-the-art to improve.

Related links:
https://github.com/tdunning/t-digest
https://github.com/marlinprotocol/mev-inspect-py

**Comment by grimadas** [comment]
Updates on the algorithm design. 

We have two metrics that we can measure each having different confidence level.

Given the total number of transactions finalised by the miner/validator - NT

1. **Violations**. For that we need to record and report the total number of violations (NV). Relative violations (RV) = NV/ NT. 
2. **Outliers**. Specifically we are interested only in extremely fast transactions, which are in top quantile compared to all other transactions. Calculate number of such outliers - NO. We can use RO = NO / NT. 
 
Finally, the miner/validator who has produced many blocks and finalised many transactions should have higher score than miners/validators who only create few blocks. 
For that we introduce miner productivity coefficient comparing. This coefficient shows how the miner compares against the top finalising miner. 

$c_i = \frac{NT_i}{max_{j \in N}(NT_j)} $ - the relative number of transaction processed by the miner against the maximum.

We use this coefficient with a sigmoid function to introduce a decay to the miner $i$:
$d_i\ =\ \frac{1}{1+e^{-12\left(c_i-0.4\right)}}$


<img width="600" alt="image" src="https://github.com/GuardianLabs/polygon-dash/assets/5897440/0615c838-b86a-47de-a2e3-510c030cd1ca">


Two metrics on outliers and violations can/should be reported in the dashboard: RO + NO, RV + NV.  

Finally, the miner score is calculated as: 

$score_i  = (0.8 * RO_i + 0.2 * RV_i) * d_i$

**Comment by ichorid** [comment]
Done
