### ISSUE TITLE
Move mempool data to Timescale DB

### ISSUE THREAD

**Issue by ichorid** [GuardianLabs/polygon-dash#38]
Historical mempool data takes _lots_ of space. Essentially, transaction occurrences at validators' mempools are a time series of events.
[Timescale DB](https://www.timescale.com/) is an AWS-hosted proprietary Postgres extension that provides an excellent opportunity to reduce our storage requirements _dozens_ of times. Basically, Timescale introduces a specialized time-series-optimized compression method for timestamps in Postgres.

We should move our Postgres instance to Timescale cloud facilities ASAP to reduce operational costs.

**Comment by Shockedshodan** [comment]
Done, migrated historical data into timescale.
